import { useState, type FormEvent } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { useCart } from "../../hooks/useCart";
import { createOrder } from "../../services/checkout.service";
import { formatCurrency } from "../../utils/currency";
import type { CustomerData } from "../../types/Order";
import "./Checkout.css";

const initial: CustomerData = { name:"", email:"", phone:"", document:"", address:"", city:"", province:"", postalCode:"", notes:"" };
export default function Checkout(){const {items,total,clearCart}=useCart();const navigate=useNavigate();const [form,setForm]=useState(initial);const [loading,setLoading]=useState(false);if(!items.length)return <Navigate to="/carrito" replace/>;const update=(key:keyof CustomerData,value:string)=>setForm(prev=>({...prev,[key]:value}));const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);try{const order=await createOrder({customer:form,items,total});sessionStorage.setItem("snaefell-last-order",JSON.stringify({id:order.id,total}));clearCart();navigate("/compra-exitosa");}finally{setLoading(false)}};return <section className="section checkout-page"><div className="container"><span className="eyebrow">Finalizar compra</span><h1 className="display-title">Checkout.</h1><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><h2>Datos de contacto y entrega</h2><div className="form-grid"><label>Nombre y apellido<input required value={form.name} onChange={e=>update("name",e.target.value)}/></label><label>Email<input required type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label>Teléfono<input required value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label>DNI / CUIT<input required value={form.document} onChange={e=>update("document",e.target.value)}/></label><label className="span-2">Dirección<input required value={form.address} onChange={e=>update("address",e.target.value)}/></label><label>Ciudad<input required value={form.city} onChange={e=>update("city",e.target.value)}/></label><label>Provincia<input required value={form.province} onChange={e=>update("province",e.target.value)}/></label><label>Código postal<input required value={form.postalCode} onChange={e=>update("postalCode",e.target.value)}/></label><label className="span-2">Notas<textarea rows={4} value={form.notes} onChange={e=>update("notes",e.target.value)}/></label></div><div className="checkout-demo-note"><strong>Modo demostración</strong><p>Este formulario crea un pedido local de prueba. La integración real con pagos debe resolverse mediante backend.</p></div><button className="button button--primary" disabled={loading}>{loading?"Procesando...":"Confirmar pedido de prueba"}</button></form><aside className="checkout-summary"><h2>Tu pedido</h2>{items.map(item=><div className="checkout-line" key={item.variantId}><span>{item.quantity} × {item.name}<small>{item.color}</small></span><strong>{formatCurrency(item.price*item.quantity)}</strong></div>)}<div className="checkout-total"><span>Total</span><strong>{formatCurrency(total)}</strong></div></aside></div></div></section>}
